### PR TITLE
Bug fix and support for timestamps

### PR DESCRIPTION
**Pull request by hmedney**
Added support for getting timestamp columns from ResultSet and for setting timestamp values in PreparedStatement.  Decided to use the string representation of the timestamp as the interchange format as it seemed the most reliable way to represent the value and avoid timezone issues.

Also fixed minor bug in ResultSet where getInt() was returning a string.

As fyi, I'm using this module in a script to copy large amounts of data from 1 database over to another.  I'll send additional PRs if I need to make any more changes.  Thanks for writing a great module!

### CODE REVIEW

**Comment by hmedney** [comment]
Hi ceyhunkerti, thanks.  You may want to regen the doc set as well. Do you need to do something special for the updates to appear on npm?

**Comment by ceyhunkerti** [comment]
Hi there,
I've published to npm too. thanks for the reminder.
I'll have a look at the docs in detail tomorrow.

**Comment by hmedney** [comment]
Hey, thanks again.  This is my first time contributing code to an open
source project - it's been an nice experience.

I just tried a fresh install from npm, and it seems to not match what's in
the repo master branch (the batch methods are there, but the new timestamp
changes aren't).  Did you publish an earlier commit to npm?

**Comment by ceyhunkerti** [comment]
sorry my mistake, i've published the latest version now.

**Comment by hmedney** [comment]
Perfect - everything looks good now.  Thanks for collaborating!

**Pull request merged**
